# Sentiment Classification of Product Reviews Using RNNs

## Read and Explore the dataset

Explore the dataset

Data Manipulations - Data Processing

Cleaning

Tokenize the reviews

Convert this into tensor. Array

Padding for small reviews

Build a model and train the model

Predict the sentiments


In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import re

In [ ]:
# from google.colab import drive
# drive.mount("/content/drive/")

In [3]:
%%writefile get_data.sh
if [ ! -f amazon_product_reviews_mod.csv ]; then
  wget -O amazon_product_reviews_mod.csv https://www.dropbox.com/scl/fi/imdwnlb4b617hfrepik8c/amazon_product_reviews_mod.csv?rlkey=3oafw8jsifa74v8hsvsuhcf77&dl=0
fi

Writing get_data.sh


In [4]:
!bash get_data.sh

--2024-02-29 14:22:48--  https://www.dropbox.com/scl/fi/imdwnlb4b617hfrepik8c/amazon_product_reviews_mod.csv?rlkey=3oafw8jsifa74v8hsvsuhcf77
Resolving www.dropbox.com (www.dropbox.com)... 162.125.13.18, 2620:100:6057:18::a27d:d12
Connecting to www.dropbox.com (www.dropbox.com)|162.125.13.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://uce074e604ced077c80693fdca71.dl.dropboxusercontent.com/cd/0/inline/COMLg9JZzcq7sxuIZYXc934W6RrV3Eg9Sswncq6m_vyqqHV2qfCW6eiv7tbu05JE4DxRLehmL5OyOIAE3mLaSZY4aEcIzvM7zypjGZF9uycKKO6-kMEyMD4PX3e9fSIHV_RCKEbCrd7Oc4sv9RWfSljj/file# [following]
--2024-02-29 14:22:49--  https://uce074e604ced077c80693fdca71.dl.dropboxusercontent.com/cd/0/inline/COMLg9JZzcq7sxuIZYXc934W6RrV3Eg9Sswncq6m_vyqqHV2qfCW6eiv7tbu05JE4DxRLehmL5OyOIAE3mLaSZY4aEcIzvM7zypjGZF9uycKKO6-kMEyMD4PX3e9fSIHV_RCKEbCrd7Oc4sv9RWfSljj/file
Resolving uce074e604ced077c80693fdca71.dl.dropboxusercontent.com (uce074e604ced077c80693fdca71.dl.dropboxusercontent.com)... 

In [5]:
!ls


amazon_product_reviews_mod.csv	get_data.sh  sample_data


In [ ]:
#cd 'drive/My Drive'

We already downloaded the dataset from [here](https://www.kaggle.com/datasets/datafiniti/consumer-reviews-of-amazon-products?select=1429_1.csv) and saved it as a CSV file which we'll read now using Pandas.

In [6]:
#path = 'HousePricePrediction.csv.csv'
# create a dataframe from csv
df = pd.read_csv('amazon_product_reviews_mod.csv')

In [7]:
df.shape    #Info on dataframe  (like display)

(28332, 4)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28332 entries, 0 to 28331
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   reviews.rating    28332 non-null  int64 
 1   reviews.text      28332 non-null  object
 2   reviews.title     28332 non-null  object
 3   reviews.username  28332 non-null  object
dtypes: int64(1), object(3)
memory usage: 885.5+ KB


In [11]:
df.iloc[101]   #look at the data (row 100)

reviews.rating                                                      4
reviews.text        Ive been buying these since they started selli...
reviews.title                                    A leaker in the pack
reviews.username                              ByCurtis Taylor Numberg
Name: 101, dtype: object

In [12]:
print(df.iloc[100]["reviews.rating"])
print(df.iloc[100]["reviews.text"])

5
As a teacher, I need tons of batteries, but I refused to spend excessive amounts on them, so I figured this was the best option! They are long-lasting, worth the money, cute (if that even matters, lol)! You won't find a deal like this in stores!I highly recommend!


In [ ]:
print(df.iloc[27162]["reviews.rating"])
print(df.iloc[27162]["reviews.text"])

5
Had to chose between Fire 10 and Fire 8. For the money, you can't go wrong with the Fire 8. Screen is good for " older eyes".


## Data Manipulations

In [17]:
reviews_df = df[["reviews.text", "reviews.rating",]]                #Just need 2 columns that are important.. so equivalent of doing select in scala.
reviews_df.columns = ["review", "rating"]

In [ ]:
reviews_df.head(10)

review  rating
0  I order 3 of them and one of the item is bad q...       3
1  Bulk is always the less expensive way to go fo...       4
2  Well they are not Duracell but for the price i...       5
3  Seem to work as well as name brand batteries a...       5
4  These batteries are very long lasting the pric...       5
5  Bought a lot of batteries for Christmas and th...       5
6  ive not had any problame with these batteries ...       5
7  Well if you are looking for cheap non-recharge...       5
8  These do not hold the amount of high power jui...       3
9  AmazonBasics AA AAA batteries have done well b...       4

In [16]:
reviews_df.isnull().sum()              ## Always check for nulls.

review    0
rating    0
dtype: int64

In [18]:
reviews_df.dropna(inplace=True)             ## If null drop the row

In [14]:
def sentiments(rating):
    if (rating == 5) or (rating == 4):
        return "positive"
    elif rating == 3:
        return "neutral"
    elif (rating == 2) or (rating == 1):
        return "negative"

In [19]:
reviews_df["sentiment"] = reviews_df["rating"].apply(sentiments)            # create a new column based on rating column called "sentiments"

In [20]:
reviews_df.sample(10, random_state = 86, ignore_index=True)

review  rating sentiment
0  perfect for plane rides. the product operates ...       5  positive
1  This suited my exact needs which was a mobile ...       5  positive
2                           Seem to last a long time       4  positive
3  I never owned a Kindle before. This was easy t...       5  positive
4   good batteries for the price. i will order again       5  positive
5  I realized after purchasing that the reason yo...       1  negative
6  I do a lot of international travelling, so I h...       5  positive
7  Bought one of these two weeks before on Amazon...       5  positive
8  I reccomend this tabley yo every one. I purcha...       5  positive
9  My granddaughter loved her tablet and the colo...       5  positive

In [21]:
sentiments = reviews_df["sentiment"].values
reviews = reviews_df["review"].values
print(sentiments[0:5])
print("\n")
print(reviews[0:5])

['neutral' 'positive' 'positive' 'positive' 'positive']


['I order 3 of them and one of the item is bad quality. Is missing backup spring so I have to put a pcs of aluminum to make the battery work.'
 'Bulk is always the less expensive way to go for products like these'
 'Well they are not Duracell but for the price i am happy.'
 'Seem to work as well as name brand batteries at a much better price'
 'These batteries are very long lasting the price is great.']


## Convert text categories into one-hot encoded vector

We are importing keras utils here, this will be needed to convert the labels to one-hot encoded vectors. We'll use the the function "to_categorical" from this library to do this. To know more about this function, please check out this [link](https://www.tensorflow.org/api_docs/python/tf/keras/utils/to_categorical).

1. Tensorflow
2. PyTorch
3. Keras

%pip install tensorflow

In [28]:
import tensorflow.keras.utils as ku


Keras to-categorical function takes numerical arguments, that's why we need to convert the text labels to numerical values first. To achieve this, we'll define this funnction.

In [22]:
# Label Encoding -- the reason being.. Model doesn't like chars.. needs number..So, labeling the sentiment to 0 1 ..
def encode_sentiments(sentiment):
    if sentiment == "negative":
        return 0
    elif sentiment == "neutral":
        return 1
    elif sentiment == "positive":
        return 2

In [24]:
label_encoding = {0: 'negative', 1: 'neutral', 2: 'positve'}

In [25]:
sentiments_encoded = [encode_sentiments(sentiment) for sentiment in sentiments]

In [26]:
print(sentiments[0:10])
print(sentiments_encoded[0:10])

['neutral' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'neutral' 'positive']
[1, 2, 2, 2, 2, 2, 2, 2, 1, 2]


In [29]:
labels = ku.to_categorical(sentiments_encoded, num_classes = 3)

In [ ]:
print(labels[0:20])
sentiments[0:20]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


array(['neutral', 'positive', 'positive', 'positive', 'positive',
       'positive', 'positive', 'positive', 'neutral', 'positive',
       'positive', 'neutral', 'positive', 'positive', 'positive',
       'positive', 'negative', 'negative', 'positive', 'neutral'],
      dtype=object)

## Cleaning of the review texts

In [30]:
## NLP -- Natural Language Processing    (clean up the language.. make it consistent)
## Like really really  means  very.. letting model know to change these type of things

test_str = "I am really really impressed by this product."
print(test_str)
old_pattern = "really"
new_pattern = "very"
new_str = re.sub(old_pattern, new_pattern, test_str)
print(new_str)

I am really really impressed by this product.
I am very very impressed by this product.


In [31]:
## NLP -- Natural Language Processing    (clean up the language.. make it consistent)
## Digits inn the review means nothing.. changing that to NLP

test_str = "Python 3.8"
print(test_str)
old_pattern = r'\d'
new_pattern = '<digit>'
new_str = re.sub(old_pattern, new_pattern, test_str)
print(new_str)

Python 3.8
Python <digit>.<digit>


### Remove hyperlinks

In [32]:
test_str = "Visit https://www.amazon.com for more information on this."
test_pattern = r'http\S+'
print(test_str)
new_str = re.sub(test_pattern, " ", test_str)
print(new_str)

Visit https://www.amazon.com for more information on this.
Visit   for more information on this.


In [33]:
def remove_hyperlinks(text):
    pattern_for_hyperlink = r'http\S+'
    return re.sub(pattern_for_hyperlink, " ", text)

In [ ]:
reviews = [remove_hyperlinks(review) for review in reviews]

In [34]:
reviews[0:5]

array(['I order 3 of them and one of the item is bad quality. Is missing backup spring so I have to put a pcs of aluminum to make the battery work.',
       'Bulk is always the less expensive way to go for products like these',
       'Well they are not Duracell but for the price i am happy.',
       'Seem to work as well as name brand batteries at a much better price',
       'These batteries are very long lasting the price is great.'],
      dtype=object)

### Expand contracted words

In [35]:
## NLP -- Natural Language Processing    (clean up the language.. make it consistent)
## Like change can't to cannot etc..

def remove_contracted_words(text):
    text = re.sub(r"won't", "will not", text)
    text = re.sub(r"can\'t", "can not", text)
    text = re.sub(r"n\'t", " not", text)
    text = re.sub(r"\'re", " are", text)
    text = re.sub(r"\'s", " is", text)
    text = re.sub(r"\'d", " would", text)
    text = re.sub(r"\'ll", " will", text)
    text = re.sub(r"\'t", " not", text)
    text = re.sub(r"\'ve", " have", text)
    text = re.sub(r"\'m", " am", text)
    return text

In [36]:
test_str = "I can't use this product. I don't recommend this product to anyone."
print(test_str)
print(remove_contracted_words(test_str))

I can't use this product. I don't recommend this product to anyone.
I can not use this product. I do not recommend this product to anyone.


In [39]:
## changing this in a for loop

reviews = [remove_contracted_words(review) for review in reviews]

In [40]:
reviews[0:5]

['I order 3 of them and one of the item is bad quality. Is missing backup spring so I have to put a pcs of aluminum to make the battery work.',
 'Bulk is always the less expensive way to go for products like these',
 'Well they are not Duracell but for the price i am happy.',
 'Seem to work as well as name brand batteries at a much better price',
 'These batteries are very long lasting the price is great.']

### Remove everything other than letters of alphabet

In [38]:
def remove_non_letters(text):
    antipattern = r'[^A-Za-z]+'
    return re.sub(antipattern, " ", text)

In [41]:
reviews = [remove_non_letters(review) for review in reviews]
reviews[0:5]

['I order of them and one of the item is bad quality Is missing backup spring so I have to put a pcs of aluminum to make the battery work ',
 'Bulk is always the less expensive way to go for products like these',
 'Well they are not Duracell but for the price i am happy ',
 'Seem to work as well as name brand batteries at a much better price',
 'These batteries are very long lasting the price is great ']

In [42]:
test_string = "I recommend      resolution with   GB of RAM     "
test_string_list = test_string.split()
test_string_list

['I', 'recommend', 'resolution', 'with', 'GB', 'of', 'RAM']

In [ ]:
' '.join(test_string_list)

'I recommend resolution with GB of RAM'

In [43]:
test_string = "       I do not like this product     "
test_string.strip()

'I do not like this product'

In [44]:
test_string = "I did not like Deliver Package provided by AMAZON"
test_string.lower()

'i did not like deliver package provided by amazon'

In [46]:
### Change the case..  Don't care for emotions that reviewer is having putting in UPPERCASE
def remove_spaces_and_convert_to_Lowercase(text):
    return ' '.join(text.split()).strip().lower()

In [47]:
reviews = [remove_spaces_and_convert_to_Lowercase(review) for review in reviews]
reviews[0:5]

['i order of them and one of the item is bad quality is missing backup spring so i have to put a pcs of aluminum to make the battery work',
 'bulk is always the less expensive way to go for products like these',
 'well they are not duracell but for the price i am happy',
 'seem to work as well as name brand batteries at a much better price',
 'these batteries are very long lasting the price is great']

## Tokenization

In [48]:
### IF we were using OpenAI, we could have used tiktoken.. Since we are doing this from basic.. we are using a basic keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [49]:
VOCAB_SIZE = 30000
UNK_TOK = '<UNK>'

In [50]:
tokenizer = Tokenizer(num_words = VOCAB_SIZE, oov_token=UNK_TOK)

In [51]:
tokenizer.fit_on_texts(reviews)

In [52]:
sequences = tokenizer.texts_to_sequences(reviews)

In [ ]:
print(sequences[0])
print(sequences[3])
print(reviews[0])
print(reviews[3])

[3, 313, 14, 38, 4, 42, 14, 2, 252, 9, 350, 92, 9, 1348, 1410, 2172, 28, 3, 17, 5, 177, 8, 3575, 14, 3945, 5, 240, 2, 64, 55]
[138, 5, 55, 16, 53, 16, 104, 96, 15, 47, 8, 82, 88, 25]
i order of them and one of the item is bad quality is missing backup spring so i have to put a pcs of aluminum to make the battery work
seem to work as well as name brand batteries at a much better price


## Padding

In [53]:
# Some reviews (input) can be very small, some reviews can be very big.. We need to standardize the size of the input (features). That's why we use padding.
# Padding means, gets the common size of the feature or input (in this case reviews)

from tensorflow.keras.preprocessing.sequence import pad_sequences

In [54]:
MAX_LEN = 32 # 32 words in my review

In [57]:
###If the reviews are less than 32 words, add "zero".. Padding is done after the reviews.
padded_sequences = np.array(pad_sequences(sequences,
                                          maxlen=MAX_LEN,
                                          padding='post',
                                          truncating='post'))

In [59]:
### You will see that the input is all of the same size.. Smaller review will get more 0
print(padded_sequences[0])
print(padded_sequences[1])
print(padded_sequences[3])

[   3  313   14   38    4   42   14    2  252    9  350   92    9 1349
 1411 2172   28    3   17    5  177    8 3579   14 3948    5  240    2
   64   55    0    0]
[532   9 181   2 216 209 167   5 137   7 296  51  30   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[138   5  55  16  53  16 104  96  15  47   8  82  88  25   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0]


## Create the model

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, SimpleRNN, Flatten, Dense

In [ ]:
model = Sequential()
model.add(Embedding(VOCAB_SIZE, 16, input_length=MAX_LEN))
model.add(Bidirectional(SimpleRNN(64, return_sequences=True)))
model.add(Bidirectional(SimpleRNN(64)))
model.add(Flatten())
model.add(Dense(24, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 32, 16)            480000    
                                                                 
 bidirectional (Bidirection  (None, 32, 128)           10368     
 al)                                                             
                                                                 
 bidirectional_1 (Bidirecti  (None, 128)               24704     
 onal)                                                           
                                                                 
 flatten (Flatten)           (None, 128)               0         
                                                                 
 dense (Dense)               (None, 24)                3096      
                                                                 
 dense_1 (Dense)             (None, 3)                 7

## Model training

In [ ]:
model.fit(padded_sequences, labels, epochs=10, validation_split=0.2)

Epoch 1/10
709/709 [==============================] - 39s 48ms/step - loss: 0.3465 - accuracy: 0.8986 - val_loss: 0.2190 - val_accuracy: 0.9367
Epoch 2/10
709/709 [==============================] - 30s 43ms/step - loss: 0.2288 - accuracy: 0.9258 - val_loss: 0.1760 - val_accuracy: 0.9481
Epoch 3/10
709/709 [==============================] - 31s 44ms/step - loss: 0.1710 - accuracy: 0.9447 - val_loss: 0.1572 - val_accuracy: 0.9515
Epoch 4/10
709/709 [==============================] - 33s 47ms/step - loss: 0.1184 - accuracy: 0.9621 - val_loss: 0.1245 - val_accuracy: 0.9674
Epoch 5/10
709/709 [==============================] - 32s 45ms/step - loss: 0.0848 - accuracy: 0.9731 - val_loss: 0.1019 - val_accuracy: 0.9756
Epoch 6/10
709/709 [==============================] - 31s 44ms/step - loss: 0.0669 - accuracy: 0.9794 - val_loss: 0.0913 - val_accuracy: 0.9816
Epoch 7/10
709/709 [==============================] - 30s 43ms/step - loss: 0.0494 - accuracy: 0.9848 - val_loss: 0.0914 - val_accuracy:

## Sentiment prediction using trained model

In [ ]:
positive_sample = 'ws husband and uncle they \
loved it and how easy they are to use with fantastic featuresi gave this as a christmas gift to my inla'

negative_sample = 'if ads dont bother you then this may be a decent device purchased this \
for my kid and it was loaded down with so much spam it kept loading it up making \
it slow and laggy plus the carrasoul loadout makes it hard to navigate for kids \
not very kid friendly oh you can pay to remove the ads but it wont remove them all \
buy the samsung better everything'

neutral_sample='it is terrible'

In [ ]:
sample_sequence = tokenizer.texts_to_sequences([negative_sample])[0]
sample_sequence_padded = pad_sequences([sample_sequence],
                                       maxlen=MAX_LEN,
                                       padding='post',
                                       truncating='post')

In [ ]:
label_encoding={0:'Negative', 1:'Neutral', 2:'Positive'}

In [ ]:
from sklearn.preprocessing import LabelEncoder

predictions = model.predict(sample_sequence_padded, verbose=0)
print(np.round(predictions, 3))
predicted_label = np.argmax(predictions, axis=1)[0]
print("Review:", neutral_sample)
print("Sentiment:", label_encoding[predicted_label])

[[0.659 0.332 0.009]]
Review: it is terrible
Sentiment: Negative
